### ISSUE TITLE
Plugin crashes when used in Next.js v8 projects

### ISSUE THREAD

**Issue by disintegrator** [honeybadger-io/honeybadger-webpack#85]
## What happens?
We are using this plugin in a Next.js v8 project that uses webpack 4.29.0 underneath and enables the upcoming webpack 5 asset emitting logic. With this logic enabled, plugin developers can no longer access an asset's contents in the afterEmit phase. As a result, this plugin causes our build to crash.

## What were you expecting to happen?
Build succeeds and source maps are uploaded

## Any logs, error output, etc?
```
/opt/app-root/src/node_modules/webpack/lib/Compiler.js:661
		throw this._error();
		^

Error: Content and Map of this Source is no longer available (only size() is supported)
    at SizeOnlySource._error (/opt/app-root/src/node_modules/webpack/lib/Compiler.js:647:10)
    at SizeOnlySource.source (/opt/app-root/src/node_modules/webpack/lib/Compiler.js:661:14)
    at HoneybadgerSourceMapPlugin.uploadSourceMap (/opt/app-root/src/node_modules/@honeybadger-io/webpack/dist/HoneybadgerSourceMapPlugin.js:157:67)
    at /opt/app-root/src/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/opt/app-root/src/node_modules/async/dist/async.js:1069:9)
    at eachOf (/opt/app-root/src/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/opt/app-root/src/node_modules/async/dist/async.js:3172:5)
    at HoneybadgerSourceMapPlugin.uploadSourceMaps (/opt/app-root/src/node_modules/@honeybadger-io/webpack/dist/HoneybadgerSourceMapPlugin.js:173:23)
    at HoneybadgerSourceMapPlugin.afterEmit (/opt/app-root/src/node_modules/@honeybadger-io/webpack/dist/HoneybadgerSourceMapPlugin.js:74:12)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/app-root/src/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/opt/app-root/src/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/opt/app-root/src/node_modules/webpack/lib/Compiler.js:432:27)
    at /opt/app-root/src/node_modules/neo-async/async.js:2813:7
    at done (/opt/app-root/src/node_modules/neo-async/async.js:3521:9)
    at outputFileSystem.writeFile.err (/opt/app-root/src/node_modules/webpack/lib/Compiler.js:400:9)
at /opt/app-root/src/node_modules/graceful-fs/graceful-fs.js:45:10
```

## Any other comments?
I am not sure what the fix is for this problem. My guess is to hook on to emit instead of afterEmit.
Webpack decided to go with this change in behaviour because it greatly reduces memory usage during build as the in-memory assets are garbage collected after being written to disk. Next.js has decided to enable this feature in webpack v4 using the `output.futureEmitAssets` flag. See: https://github.com/webpack/webpack/releases/tag/v4.29.0
We use `source-map` as the webpack `devtool` option value.

## What versions are you using?
**Package Version:**
* @honeybadger-io/webpack: 1.1.4
* next: 8.0.1
* webpack: 4.29.0

**Comment by disintegrator** [comment]
Related: https://github.com/thredup/rollbar-sourcemap-webpack-plugin/issues/61

**Comment by joshuap** [comment]
@disintegrator thanks, we'll take a look. Binding to `emit` may also fix #52. I'm not sure off the top of my head if it will work for our use case, though.

**Comment by paambaati** [comment]
@disintegrator Were you able to fix this? I’m running Next.js 9 and I’m considering using Honeybadger. I’d appreciate it a lot if you can share how you integrated them.

**Comment by joshuap** [comment]
I'm digging into this this week. Let me know if any of you have instructions you can share, otherwise I'll update this when I know more!

**Comment by joshuap** [comment]
I have this working in the latest version of next (9.4) here:

https://github.com/honeybadger-io/nextjs-with-honeybadger

The Webpack config is here:

https://github.com/honeybadger-io/nextjs-with-honeybadger/blob/master/next.config.js#L21

As a bonus, it also supports isomorphic error reporting (see [pages/_app.js](https://github.com/honeybadger-io/nextjs-with-honeybadger/blob/master/pages/_app.js)). :) If you have this set up a different way, you can remove the `config.resolve.alias` option in the Webpack config.

See the [About](https://github.com/honeybadger-io/nextjs-with-honeybadger#about-example) section in the README for more info.

If you try it out it would be great if you report back on how it works for you!

**Comment by paambaati** [comment]
@joshuap I just skimmed the repo a bit, and it looks super-comprehensive. Fantastic work!

I’d also recommend submitting this as PR to the Next.js project, as an addition to the `examples/` directory. That would be helpful to Next.js users looking to try/use Honeybadger, and as a bonus, you get community help in maintaining it.
